### ISSUE TITLE
Still uses CPU

### ISSUE THREAD

**Issue by WindowsNT** [eloimoliner/denoising-historical-recordings#10]
It looks nice, I am trying to install with pip:

pip install hydra-core tensorflow[and-cuda] soundfile tqdm scipy 
python inference.py inference.audio="r:\9.mp3"

it works with the CPU (slow) although I have a GPU and tensorflow[and-cuda] is installed. What am I missing?
Or, is the GPU stuff training-only?

**Comment by eloimoliner** [comment]
Inference should work in GPU. I guess there is some version issue with the CUDA and/or tensorflow installations.

**Comment by WindowsNT** [comment]
I found the issue, tensorflow doens't anymore support native CUDA gpu on Windows :(
