### ISSUE TITLE
installation without conda

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [eloimoliner/denoising-historical-recordings#2]
Hi, 

could you leave some hints about how to install this without conda?
Your readme appears to be very much specified to this one case. 
Also it seems that you develop under linux so you use bash to execute. Maybe here a hint for win- users would be cool too. 

I am just trying to get this to run under windows and so far had no success. I will update if I get further. 
All the best!

**Comment by eloimoliner** [comment]
Hello,

Thanks for your interest in our work.  To install this in your windows environment you must have python 3.7 and the rest of dependencies. You can see the full list in environment.yaml. The most restricting one is tensorflow 2.3.0, so I would start with this one (using pip for example) and then install the rest. If you have the correct versions of the dependencies, it should work. I haven't tried running this code in windows so maybe there will be other unexpected problems you will have to troubleshoot (I hope not though). I could try to help with this. 

 Also remember to download the weights and add them in the proper folder (/experiments/trained_model/). 

Note also that the bash scripts I use are quite simple, so you can easily convert them to batch an run them on windows, or just run directly the python script in your cmd. 

Good luck!

**Comment by GitHubGeniusOverlord** [comment]
Here is what I did so far:
#make venv:
cd to path
python -m venv venv_denoise
.\venv_denoise\Scripts\activate

#Install single libraries which have versions that need to differ from specs in requirements.txt (pip said this)
cd venv_denoise\Scripts\
python -m pip install --upgrade pip
python -m pip install scipy==1.6.0
python -m pip install tensorflow==2.5.0
python -m pip install h5py #Without version because pip didn't recommend andy
python -m pip install gast==0.4.0
python -m pip install grpcio==1.34.0
python -m pip install numpy==1.19.3
python -m pip install six==1.15.0
python -m pip install tensorflow-estimator==2.5.0
python -m pip install typing-extensions==3.7.4

#Remove above packages from requirements.txt
#Install from requirements
Python -m pip install -r path\requirements.txt

#run
python path\inference.py path_experiment="path\experiments\trained_model" inference.audio="path_to_audio"

##########################
What happens:
It starts doing something but breaks.
The error indicates that gpu memory is not sufficient. I have 4GB dedicated GPU memory here. Maybe not enough?

`2022-01-19 18:26:15.295916: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at mirror_pad_op.cc:120 : Resource exhausted: OOM when allocating tensor with shape[1,64,1725,1027] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
  0%|                                                                                        | 0/10 [00:17<?, ?it/s]
[2022-01-19 18:26:15,296][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\denoising-historical-recordings\inference.py", line 150, in main
    _main(args)
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\denoising-historical-recordings\inference.py", line 144, in _main
    run(args)
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\denoising-historical-recordings\inference.py", line 81, in run
    pred = unet_model.predict(segment_TF_ds.batch(1))
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1727, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\eager\def_function.py", line 956, in _call
    return self._concrete_stateful_fn._call_flat(
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\eager\function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\seu\Desktop\2021_Projekte\20210901_Pytorch_HQA\Two-Stage-Denoising\venv_denoise\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[1,64,1725,1027] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model/multi_stage_denoise/StatefulPartitionedCall/encoder/e__block/i__block/dense_block/MirrorPad_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_predict_function_11989]`

**Comment by eloimoliner** [comment]
I'll bet you are running out of memory. Try reducing the segment size, it was 20s by default (quite large). Change this line:
https://github.com/eloimoliner/denoising-historical-recordings/blob/4b78316889881bf28cc32a242b2c4d89df8a1285/inference.py#L62

segment_size=44100*5

**Comment by GitHubGeniusOverlord** [comment]
Hello eloimoliner, 

it works now. Wonderful! 
Maybe you may want to add the learnings about running it on windows and on machines with less gpu memory to your readme! 
Let me also say that this is the best denoising tool I have ever seen. Maybe the creation of a colab or a windows gui for it would be worthwile as well.

**Comment by eloimoliner** [comment]
That's great! Thanks for the feedback! :) It is a great idea to create a colab so that people could try it easily, I will consider doing it.  I also have in mind to update the readme. I'm also planning to release a pytorch version of the code soon.

**Comment by GitHubGeniusOverlord** [comment]
I am at the moment working on a command-statement creator-class for the denoiser. I want to have it iterate over multiple files in a folder. Creating and pasting that super long string into cmd is not very practical. Would you be interested in that feature?

**Comment by eloimoliner** [comment]
I'm not use what you mean with command-statement creator-class. When I wanted to iterate over multiple files I just did it with a simple bash script:
`  for audio in $(ls   $PATH_BASE/*.wav)
   do        
      python inference.py path_experiment="experiments/trained_model" inference.audio=$audio
   done     
`
But if you develop an utility that makes this tool easier to use, I would be happy if you share it :)

**Comment by GitHubGeniusOverlord** [comment]
What I meant:
I believe that bash scripts dont work under windows. Or maybe they do and I dont know how to use them. Thats why I thought of a way to create the whole cmd-statement as a string in python and run it from there. 
The reason to do it that way is probably also that I am used to executing python code. 
In the end I am not sure how to best approach this. Maybe there is a better solution. I am happy to discuss those things. If you want to start your colab, I will probably make suggestions too. 
I dont't want to abuse this issue as a chat, but may I ask how I can contact you for further discussions?

**Comment by eloimoliner** [comment]
Ok, I think I understand.  So you basically want to simplify the command with this solution, right? But I am not sure if doing it this way would simplify things much. I'm not used to work in windows, so I don't know what would be the easiest way to execute that there. I previously thought about putting everything into a docker, but I don't have much experience with these. 
In fact, the "path_experiment" attribute can be omitted if the proper path is added by default in hydra's conf file, that would make the command shorter.  I will update that in the next commit. 

Please, contact me here: eloi.moliner@aalto.fi
