### ISSUE TITLE
strange tensorflow version in requirements.txt

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [eloimoliner/denoising-historical-recordings#3]
Hi,

when running 
python -m pip install tensorflow==2.3.0 as indicated in your requirements file, I get 

ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0)
ERROR: No matching distribution found for tensorflow==2.3.0

It seems this version isn't even supported by pip anymore. 
Upgrade to 2.5.0?

The same is true for scipy==1.4.1. Not sure about which version to take there.

**Comment by eloimoliner** [comment]
Hi,

Which version of python do you have? I used python 3.7 in my environment. 

Otherwise, it could also work if you use  newer versions of these packages, I guess.

**Comment by GitHubGeniusOverlord** [comment]
I am using python version 3.9.6.
When I can't install a package ill go up in the version-number. Let me try that and see how far I get.

**Comment by GitHubGeniusOverlord** [comment]
Solution in 
https://github.com/eloimoliner/denoising-historical-recordings/issues/2
