### ISSUE TITLE
How to start training for denoising? 

### ISSUE THREAD

**Issue by listener17** [eloimoliner/denoising-historical-recordings#5]
If I would like to do a denoising task, where I've clean signals (in the "clean" folder) and noisy signals (in the "noise" folder).

**Comment by eloimoliner** [comment]
Hi,
The code is prepared for training with a dataset of clean signals and another dataset of noises (no music).  The directories of both datasets are specified in "conf/dset/dataset.yaml"  in "path_music_train" and "path_noise".  
For the noises, I used the Gramophone Noise Dataset, which is publicly available here: "http://research.spa.aalto.fi/publications/papers/icassp22-denoising/" 
The dataset_loader.py mixes the clean data and the gramophone noises in a random way, but take into account that it looks at the "info.csv" file from this dataset. If you want to retrain using different data, you will probably have to modify the dataset_loader.py.
 You could also train having some set of paired clean and noisy signals, but you should build your own data loader, which should not be too difficult (I guess).

Good luck!
